config/routes.rb
CatLottery::Application.routes.draw do
  devise_for :users

  
  resources :events do
    resources :cats do
    end
    
    collection do
      get :lottery
    end
  end
  

  root :to => 'events#index'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates_presence_of :name
  validates_length_of :name, maximum: 50
  belongs_to :event
  
  #scope :lottery, order: 'random()', limit: @quantity  
  scope :lottery, lambda{|quantity| order('random()').limit(quantity)}

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :description
  
  has_many :cats
  has_many :prizes
  belongs_to :user
  
  scope :lottery, lambda{|quantity| order('random()').limit(quantity)}
  
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  
  belongs_to :event
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :events
  
  def is_admin?
    is_admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cats_controller.rb
# encoding: utf-8
class CatsController < ApplicationController
  
  def index
    @cats = Cat.all
    
    @event = Event.find(params[:event_id])
    redirect_to event_path(@board)
  end
  
  def new
    @event = Event.find(params[:event_id])
    @cat = @event.cats.build
  end
  
  def create
    @event = Event.find(params[:event_id])
    @cat = @event.cats.build(params[:cat])
    
    if @cat.save
      flash[:notice] = "成功加入"
      redirect_to event_cat_path(@event, @cat)
    else
      redirect_to new_event_cat_path
    end
  end
  
  def show
    @event = Event.find(params[:event_id])
    @cat = @event.cats.find(params[:id])
    @page_title = @cat.name
  end
  
  def edit
    @event = Event.find(params[:event_id])
    @cat = @event.cats.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:event_id])
    @cat = @event.cats.find(params[:id])
    
    if @cat.update_attributes(params[:cat])
      flash[:notice] = "成功更新"
      redirect_to event_cat_path(@event,@cat)
    else
      redirect_to edit_event_cat_path
    end
  end
  
  def destroy
    @event = Event.find(params[:event_id])
    @cat = @event.cats.find(params[:id])
    flash[:alert] = "成功刪除"
    @cat.destroy
    redirect_to event_path(@event)
  end
  
  #def lottery
    #list_count = Cat.count
    #@cats = Cat.lottery(params[:quantity])
  #end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :find_event, only: [ :show, :edit, :update, :destroy]
  before_filter :check_user, except: [:index]
  
  def index
    if (current_user)
      @user = current_user
      @events = @user.events.all
    end
  end
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.new(params[:event])
    @event.user_id = current_user.id
    @event.save
    
    redirect_to events_path
  end
  
  def show
    @page_title = @event.name
    @cats = @event.cats
    
  end
  
  def edit
    
  end
  
  def update
    if @event.update_attributes(params[:event])
      redirect_to event_path(@event)
    else
      redirect_to edit_event_path
    end
  end
  
  def destroy
    @event.destroy
    redirect_to events_path
  end
  
  def lottery
    @event = Event.find(params[:id])
    @cats = @event.cats.lottery(params[:quantity])
  end
  
  protected
  def find_event
    @event = Event.find(params[:id])
  end
  
  protected
  def check_user
    if !user_signed_in?
      redirect_to root_path
    end
  end
end

app/controllers/portal_controller.rb
class PortalController < ApplicationController
  def index
    
  end

end

app/controllers/prizes_controller.rb
class PrizesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/lottery_sources_helper.rb
module LotterySourcesHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/views/cats/_form.html.erb
    <% if @cat.errors.any? %>
      <ul>
      <% @cat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    <% end %>
    
    <p>
    <%= f.label :name, "貓貓名：" %>
    <%= f.text_field :name %>
    </p>

app/views/cats/edit.html.erb
<h1>編輯貓貓資料</h1>
<%= form_for @cat, url: event_cat_path(@event, @cat), method: :put do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
    <%= f.submit "我變" %><%= link_to '不想變了', event_path(@event) %>
<% end %>

app/views/cats/index.html.erb
<h1>抽獎名單</h1>
<ul>
<% @cats.each do |list| %>
  <li>
    <%= list.name %>
    <%= link_to '顯示', cat_path(list) %>
    <%= link_to '編輯', edit_cat_path(list) %>
    <%= button_to '刪除', cat_path(list), method: :delete %>
  </li>
<% end %>
</ul>
<p>
  <%= link_to '加新貓貓', new_cat_path %>
</p>

<%= form_tag url_for(controller: 'cats', action: 'lottery'), :method => "get" do %>
  <p>想抽
  <%= text_field_tag 'quantity' %>
  隻貓</p>
  <%= submit_tag '抽！' %>
<% end %>

<% if @cats.count > 0 %>

  

<p>
  <%#= link_to '抽貓貓！', lottery_cats_path %>
</p>
<% end %>

app/views/cats/lottery.html.erb
<h1>抽到的貓貓</h1>
<p>抽到的貓貓是
<% @cats.each do |cat| %>
<br />「<%= cat.name %>」
<% end %>
</p>
 
<p><%= link_to '回名單', cats_path %></p>

app/views/cats/new.html.erb
<h1>加入新貓</h1>
<%= form_for @cat, url: event_cats_path(@event) do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
    <%= f.submit "加啦" %><%= link_to '不想加了', event_path(@event) %>
<% end %>

app/views/cats/show.html.erb
<h1>貓貓詳細資料</h1>
<p>現在只有貓貓名「<%= @cat.name %>」而已</p>
 
<p><%= link_to '回名單', event_path(@event) %></p>

app/views/common/_user_nav.erb
<div class="user_navigation">
  <% if user_signed_in? %>
    嗨! <%= current_user.email %>
    <%= link_to("登出", destroy_user_session_path, :method => :delete) %>
  <% else %>
    <%= link_to "登入", new_user_session_path %>
    <%= link_to "註冊", new_user_registration_path %>
  <% end %>
</div>

app/views/events/_form.html.erb
  <%= f.label :name, "活動名稱：" %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :description, "活動說明：" %>
  <%= f.text_area :description %>
  <br />

app/views/events/edit.html.erb
<h1>編輯活動資料</h1>
<%= form_for @event, url: event_path(@event), method: :put do |f| %>
<p>
  <%= render partial: 'form', locals: { f: f } %>
</p>
    <%= f.submit "我變" %><%= link_to '不想變了', events_path %>
<% end %>

app/views/events/index.html.erb
<h1>首頁</h1>

<% if user_signed_in? %>

你的id是 <%= current_user.id %>

<ul>
<% @events.each do |list| %>
  <li>
    <%= list.name %> - <%= list.user_id %>
    <%= link_to '顯示', event_path(list) %>
    <%= link_to '編輯', edit_event_path(list) %>
    <%= button_to '刪除', event_path(list), method: :delete %>
  </li>
<% end %>
</ul>
<p>
  <%= link_to '建立新活動', new_event_path %>
</p>

<% else %>

<%= form_for("user", :url => user_session_path) do |f| %>
  <%= f.text_field :email %> <br />
  <%= f.password_field :password %> <br />
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me %> <br />
  <%= f.submit 'Sign in' %> <br />
  <%= link_to "Forgot your password?", new_password_path('user') %>
<% end %>


<% end %>

app/views/events/lottery.html.erb
<h1>抽到的貓貓</h1>
<p>抽到的貓貓是
<% @cats.each do |cat| %>
<br />「<%= cat.name %>」
<% end %>
</p>
 
<p><%= link_to '回名單', event_path(@event) %></p>

app/views/events/new.html.erb
<% content_for :head do %>
<script src="/assets/javascripts/add_prizes_form.js" type="text/javascript"></script>
<% end %>
<h1>加入新活動</h1>
<%= form_for @event, url: events_path do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= f.submit "我加！" %>
<% end %>

app/views/events/show.html.erb
<h1>活動資料</h1>
<p>活動名稱：<%= @event.name %></p>
<p>活動說明：<%= @event.description%></p>

<%= form_tag url_for(action: 'lottery', controller: 'events'), :method => "get" do %>
  <p>想抽
  <%= text_field_tag 'quantity' %>
  隻貓</p>
  <%= hidden_field_tag "id", @event.id %>
  <%= submit_tag '抽！' %>
<% end %>

<ul>
<% @cats.each do |cat| %>
  <li>
    <%= cat.name %>
    <%= link_to '顯示', event_cat_path(@event,cat) %>
    <%= link_to '編輯', edit_event_cat_path(@event,cat) %>
    <%= button_to '刪除', event_cat_path(@event,cat),confirm: '你確定嗎？', method: :delete %>
  </li>
<% end %>
</ul>
<p><%= link_to '加新貓貓', new_event_cat_path(@event) %></p>
<p><%= link_to '編輯活動', edit_event_path(@event) %></p>
<p><%= link_to '回活動列表', events_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "抽貓貓！" %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
<p style="color: green"><%= flash[:notice] %></p>
<p style="color: red"><%= flash[:alert] %></p>
<%= render :partial => "common/user_nav" %>
<%= yield %>

</body>
</html>

app/views/lottery_sources/_form.html.erb
    <% if @lottery_source.errors.any? %>
      <ul>
      <% @lottery_source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    <% end %>
    
    <p>
    <%= f.label :name, "貓貓名：" %>
    <%= f.text_field :name %>
    </p>

app/views/portal/index.html.erb
<h1>這是首頁</h1>

<p>這樣總行了吧，會動嗎？</p>

<%= form_for("user", :url => user_session_path) do |f| %>
  <%= f.text_field :email %><br />
  <%= f.password_field :password %><br />
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me %><br />
  <%= f.submit 'Sign in' %><br />
  <%= link_to "Forgot your password?", new_password_path('user') %>
<% end %>